language: java
sudo: false # faster builds

services: docker

branches:
  only:
    - master

jdk:
  - oraclejdk8

before_install:
  - env | sort
  - name="spring-rest-api-starter"
  - TAG="travis"
  - IMAGE_NAME="monogramm/docker-spring-rest-api-starter:${TAG}"
  - dir="."

install:
  #- mvn clean install dockerfile:build -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  #- docker build --build-arg=target/*.jar -t "$IMAGE_NAME" "$dir"
  - docker build -t "$IMAGE_NAME" "$dir"
  - docker run --name "$name" -d "$IMAGE_NAME" "$dir" -eDB_PLATFORM=h2 -eAPP_VERIFIER_KEY_PASS=averysecretpasswordforjks
  - docker logs "$name"
  - docker logs "$name" | grep "Launching application..."
  - docker stop "$name"

script: 
  - mvn test verify -P all-tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
