language: java
sudo: false # faster builds

jdk:
  - oraclejdk8

install:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: 
  - mvn test site

after_success:
  - bash <(curl -s https://codecov.io/bash)
