os: linux
dist: trusty

services: docker

language: java

branches:
  only:
    - master

jdk:
  - oraclejdk11

before_install:
  - env | sort
  - export DOCKER_REPO="monogramm/spring-rest-api-starter"
  - export TAG="travis"
  - export IMAGE_NAME="${DOCKER_REPO}:${TAG}"
  - name="spring-rest-api-starter"
  - export home=$(pwd)
  - export travis_dir="${home}/."

install:
  # Test app build locally with maven
  #- mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  # Test app build through docker container
  - travis_retry docker-compose -f "docker-compose_${DATABASE}.yml" build

before_script:
  - docker images

script:
  # Execute tests locally with maven
  - mvn clean test verify -P all-tests
  # Test container run
  - travis_retry docker-compose -f "docker-compose_${DATABASE}.yml" up -d && sleep 20
  - docker-compose -f "docker-compose_${DATABASE}.yml" ps
  - docker-compose -f "docker-compose_${DATABASE}.yml" logs "app_api"
  - docker-compose -f "docker-compose_${DATABASE}.yml" ps "app_api" | grep "Up" || exit 1

after_success:
  # Send test coverage report to CodeCov
  - bash <(curl -s https://codecov.io/bash)

env: # Environments
  - DATABASE=h2
  - DATABASE=mysql
  - DATABASE=mariadb
  - DATABASE=postgres
