language: java
sudo: false # faster builds

jdk:
  - oraclejdk8

install:
  - mvn clean

build: 
  - mvn install
  - mvn test site

after_success:
  - bash <(curl -s https://codecov.io/bash)
