os: linux
dist: trusty

services: docker

language: shell

branches:
  only:
    - master

jdk:
  - oraclejdk11

before_install:
  - env | sort
  - export DOCKER_REPO="monogramm/spring-rest-api-starter"
  - export TAG="travis"
  - export IMAGE_NAME="${DOCKER_REPO}:${TAG}"
  - name="spring-rest-api-starter"
  - export home=$(pwd)
  - export travis_dir="${home}/images/${VARIANT}"

install:
  #- mvn clean install dockerfile:build -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  #- docker build --build-arg=target/*.jar -t "$IMAGE_NAME" "$dir"
  - docker build -t "$IMAGE_NAME" "$travis_dir"
  - docker run --name "$name" -d "$IMAGE_NAME" "$travis_dir" -eDB_PLATFORM=h2 -eAPP_VERIFIER_KEY_PASS=averysecretpasswordforjks
  - docker logs "$name"
  - docker logs "$name" | grep "Launching application..."
  - docker stop "$name"

script: 
  - mvn test verify -P all-tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
