#!/bin/bash

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/
# https://microbadger.com/labels

docker build \
    --build-arg "VCS_REF=$(git rev-parse --short HEAD)" \
    --build-arg "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
    --build-arg "EXPORT_TESTS_RESULTS=${EXPORT_TESTS_RESULTS:-false}" \
    -f "$DOCKERFILE_PATH" \
    -t "$IMAGE_NAME" .
