
name: Docker Image CI

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: ['alpine']

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Execute CI build hooks
        id: docker_build
        run: |
          ./hooks/run build ${{ matrix.variant }}

      - name: Display docker images
        run: docker images

      - name: Execute CI test hooks
        id: docker_test
        run: |
          export EXPORT_TESTS_RESULTS=true
          ./hooks/run test ${{ matrix.variant }}
          ls -al ./coverage

      #- name: Codacy Coverage Reporter
      #  uses: codacy/codacy-coverage-reporter-action@0.2.0
      #  with:
      #    project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
      #    coverage-reports: ./coverage/coverage-phpunit-cobertura.xml
